### ISSUE TITLE
Blis

### ISSUE THREAD

**Issue by bkmgit** [yoshoku/numo-openblas#1]
Might it be worth adding an option to use [Blis](https://github.com/flame/blis/blob/master/docs/Performance.md)?

**Comment by yoshoku** [comment]
@bkmgit Numo::OpenBLAS uses locally built OpenBLAS as a background library for Numo::Linalg. Thus, I have no plans to support BLIS, which is a library on the same layer as OpenBLAS. I think that it is better to extend Numo::Linalg to be enable to use BLIS as a background library and then to develop Numo::BLIS as needed.

**Comment by yoshoku** [comment]
@bkmgit I have released Numo::BLIS that uses locally built BLIS as a background library for Numo::Linalg like Numo::OpenBLAS. Please try it.
https://rubygems.org/gems/numo-blis

**Comment by bkmgit** [comment]
Thanks. Will try it.
